In [1]:
import os, sys
import numpy as np
util_dir = os.path.dirname('../../util/')
sys.path.insert(0, util_dir) 
import bern_metrop

In [2]:
from bern_metrop import my_data, likelihood, prior

In [3]:
likelihood(0.3, my_data)

[5.6271152e-09]


array([5.6271152e-09])

In [4]:
likelihood(np.array([0.3]), my_data)

[5.6271152e-09]


array([5.6271152e-09])

In [5]:
likelihood(np.array([0.3, 0.1, 0.9, 0.2, 1.2, 1, -1]), my_data)

[5.62711520e-09 5.31441000e-15 2.28767925e-07 4.29496730e-11
 8.21707817e-04 0.00000000e+00 6.40000000e+01]


array([5.62711520e-09, 5.31441000e-15, 2.28767925e-07, 4.29496730e-11,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [6]:
prior(0.3)

array([1.])

In [7]:
prior(np.array([0.3]))

array([1.])

In [8]:
prior(np.array([0.3, 0.1, 0.9, 0.2, 1.2, 1, -1]))

array([1., 1., 1., 1., 0., 1., 0.])